services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 2s
      timeout: 2s
      retries: 30

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ENV: development
      PORT: 8080
      DB_DSN: postgres://postgres:postgres@db:5432/app?sslmode=disable
      JWT_SECRET: please_change_me
      MEDIA_DIR: /data/media
      CORS_ORIGINS: http://localhost:5173,http://localhost:3000
    ports:
      - "8080:8080"
    volumes:
      - ./data/media:/data/media
      - ./docs:/app/docs:ro
    # untuk dev hot-reload, nanti bisa ditambah command: ["air"]

  # swagger:
  #   image: swaggerapi/swagger-ui
  #   ports:
  #     - "8081:8080"
  #   volumes:
  #     - ./docs/openapi.yaml:/openapi.yaml:ro 
  #   environment:
  #     - SWAGGER_JSON=/openapi.yaml
  #   # volumes:
  #   #  - ./docs/openapi.yaml:/usr/share/nginx/html/openapi.yaml:ro
  #   # environment:
