services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    # Security: do not expose DB ports to the public on VPS
    # ports:
    #   - "5432:5432"
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ENV: production
      PORT: 8080
      DB_DSN: postgres://postgres:postgres@db:5432/app?sslmode=disable
      JWT_SECRET: change_this_to_a_long_random_secret_value
      JWT_TTL_HOURS: "24"
      MEDIA_DIR: /data/media
      # Set to your public origin (domain or IP with http/https scheme).
      # If you access via Nginx at http://YOUR_SERVER_IP or http://your-domain.com,
      # fill in one of the following:
      CORS_ORIGINS: http://your-domain.com,http://YOUR_SERVER_IP
    expose:
      - "8080"
    volumes:
      - ./data/media:/data/media
      - ./docs:/app/docs:ro
    restart: unless-stopped
    # for dev hot-reload, add the command: ["air"]

  web:
    image: nginx:alpine
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ | grep -qi '<!doctype html>'"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  # --- Optional: dev-only ---
  # frontend:
  #   image: node:20-alpine
  #   working_dir: /app
  #   command: sh -lc "npm ci && npm run dev -- --host 0.0.0.0"
  #   ports:
  #     - "5173:5173"
  #     - "24678:24678"
  #   environment:
  #     VITE_API_URL: http://localhost:8080
  #   volumes:
  #     - ./frontend:/app
